/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An integer amount in **minor units** plus an ISO 4217 currency. `2000000` + `IDR` is
         *     Rp 20.000.
         *
         *     Never a float and never a decimal string. IDR has no minor unit in practice, but the
         *     scale of 2 is kept uniform so multi-currency is not a migration.
         */
        Money: {
            /**
             * Format: int64
             * @example 19900000
             */
            amount: number;
            /** @example IDR */
            currency: string;
        };
        /**
         * @description The canonical error codes for this phase. The code also appears as the last segment of a
         *     `Problem.type` URI, and directly in per-row results where an operation partially succeeds
         *     — see `API spec.md` §6.2.
         * @enum {string}
         */
        ErrorCode: "validation_failed" | "version_conflict" | "duplicate_sku" | "permission_denied" | "not_found" | "rate_limited";
        /**
         * @description One field-level detail inside a `Problem`. Carries whatever the specific failure needs —
         *     a version conflict reports `expected` and `supplied`, a validation failure reports a
         *     message — so extra properties are permitted by design.
         */
        ProblemError: {
            /** @example version */
            field: string;
            detail?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description RFC 9457 `application/problem+json`. Every error response in this API uses it.
         *
         *     `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
         *     the span. There is no separate `code` field: the code is the last segment of `type`.
         */
        Problem: {
            /**
             * Format: uri
             * @example https://docs.example.com/errors/version-conflict
             */
            type: string;
            /** @example Version conflict */
            title: string;
            /** @example 409 */
            status: number;
            /** @example Product was modified by another user. Reload and retry. */
            detail?: string;
            /** @example /v1/products/01926f3a-0000-7000-8000-000000000000 */
            instance?: string;
            /** @example 4bf92f3577b34da6a3ce929d0e0e4736 */
            trace_id: string;
            errors?: components["schemas"]["ProblemError"][];
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, expired or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated but not permitted. `detail` names the permission that was required. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description No such resource **in this tenant**. A row belonging to another tenant is indistinguishable
         *     from one that does not exist, which is the intended behaviour.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `version_conflict` when `If-Match` is stale, or `duplicate_sku` when a SKU is already
         *     taken within the tenant.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Validation failed. Also returned when a client sends a server-managed field on update, or
         *     sends `null` where the field should simply have been omitted — those are not the same
         *     thing.
         */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded. See the `RateLimit-*` headers. */
        TooManyRequests: {
            headers: {
                "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Page size. Pairs with `cursor`; there is no `offset` in this API. */
        Limit: number;
        /**
         * @description Opaque cursor from the previous page. Cursor pagination only — a deep `offset` on a large
         *     table is a sequential scan, so the parameter does not exist.
         */
        Cursor: string;
        /**
         * @description The `version` read from the resource. Required on every `PATCH`. The server checks it in
         *     the `UPDATE … WHERE version = $n` predicate; a stale value is `409 version_conflict`, not
         *     a silent no-op.
         *
         *     `version` travels here and never in the request body.
         */
        IfMatch: number;
    };
    requestBodies: never;
    headers: {
        /** @description Requests permitted in the current window. */
        "RateLimit-Limit": number;
        /** @description Requests left in the current window. */
        "RateLimit-Remaining": number;
        /** @description Seconds until the window resets. */
        "RateLimit-Reset": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
