/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an email and password for an access token
         * @description The tenant is resolved from the user row -- `email` is unique across the whole system, so
         *     it identifies exactly one user and therefore exactly one tenant. There is deliberately no
         *     tenant, workspace or subdomain parameter.
         *
         *     On success the refresh token is set as an httpOnly, Secure, SameSite=Lax cookie. It is
         *     never in the response body, where a script could read it.
         *
         *     A wrong password, an unknown email and a disabled account all return the same `401`. Any
         *     difference between them tells an attacker which emails exist.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and issue a new access token
         * @description Reads the refresh token from the cookie, never from the body. Unauthenticated by
         *     necessity -- this is what you call *because* the access token has expired.
         *
         *     Each call issues a new refresh token and revokes the one presented. **Presenting a token
         *     that was already rotated means it was stolen**: the entire rotation chain is revoked and
         *     every session for that user ends, rather than that one request being rejected.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current refresh token
         * @description Revokes the refresh token in the cookie and clears it. The access token is not revoked --
         *     it is stateless and expires on its own within 15 minutes.
         *
         *     Idempotent: logging out twice, or with no cookie at all, is still `204`. There is nothing
         *     useful to tell a caller about a session that is already gone.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The five seeded roles and the permissions each grants
         * @description Fixed and identical for every tenant. Phase 1 has no custom roles and no per-user
         *     overrides, so this is a constant -- it exists so a client can render a role picker and
         *     explain what a role means without hardcoding the matrix from `API spec.md` §3.
         *
         *     Requires `users:read`, because it is part of the team-management surface. An `ops` user
         *     gets `403` naming that permission, which is `flows.md` §6's acceptance criterion.
         */
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /**
             * Format: email
             * @example ops@erigo.co.id
             */
            email: string;
            /** Format: password */
            password: string;
        };
        /**
         * @description Returned by both login and refresh. Carries everything the client needs to render a
         *     signed-in shell without a second request.
         *
         *     The refresh token is **not** here -- it is in an httpOnly cookie, out of reach of any
         *     script on the page.
         */
        Session: {
            /** @description JWT. Held in memory only, never in localStorage. */
            access_token: string;
            /**
             * @description Seconds until the access token expires.
             * @example 900
             */
            expires_in: number;
            user: components["schemas"]["SessionUser"];
            tenant: components["schemas"]["SessionTenant"];
        };
        SessionUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "admin" | "ops" | "warehouse" | "viewer";
            /**
             * @description `resource:action` strings the role grants. The client hides actions it does not find
             *     here rather than disabling them -- a button that 403s advertises a capability the user
             *     does not have.
             */
            permissions: string[];
        };
        SessionTenant: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * @description IANA name. Applied at render time only; the wire is always UTC.
             * @example Asia/Jakarta
             */
            timezone: string;
            /** @example IDR */
            currency: string;
        };
        /** @description One of the five seeded roles and everything it grants. */
        Role: {
            /** @enum {string} */
            name: "owner" | "admin" | "ops" | "warehouse" | "viewer";
            /** @description One line a client can show next to the role in a picker. */
            description?: string;
            permissions: string[];
        };
        /**
         * @description An integer amount in **minor units** plus an ISO 4217 currency. `2000000` + `IDR` is
         *     Rp 20.000.
         *
         *     Never a float and never a decimal string. IDR has no minor unit in practice, but the
         *     scale of 2 is kept uniform so multi-currency is not a migration.
         */
        Money: {
            /**
             * Format: int64
             * @example 19900000
             */
            amount: number;
            /** @example IDR */
            currency: string;
        };
        /**
         * @description The canonical error codes for this phase. The code also appears as the last segment of a
         *     `Problem.type` URI, and directly in per-row results where an operation partially succeeds
         *     — see `API spec.md` §7.2.
         * @enum {string}
         */
        ErrorCode: "validation_failed" | "version_conflict" | "duplicate_sku" | "permission_denied" | "not_found" | "rate_limited";
        /**
         * @description One field-level detail inside a `Problem`. Carries whatever the specific failure needs —
         *     a version conflict reports `expected` and `supplied`, a validation failure reports a
         *     message — so extra properties are permitted by design.
         */
        ProblemError: {
            /** @example version */
            field: string;
            detail?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description RFC 9457 `application/problem+json`. Every error response in this API uses it.
         *
         *     `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
         *     the span. There is no separate `code` field: the code is the last segment of `type`.
         */
        Problem: {
            /**
             * Format: uri
             * @example https://docs.example.com/errors/version-conflict
             */
            type: string;
            /** @example Version conflict */
            title: string;
            /** @example 409 */
            status: number;
            /** @example Product was modified by another user. Reload and retry. */
            detail?: string;
            /** @example /v1/products/01926f3a-0000-7000-8000-000000000000 */
            instance?: string;
            /** @example 4bf92f3577b34da6a3ce929d0e0e4736 */
            trace_id: string;
            errors?: components["schemas"]["ProblemError"][];
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, expired or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Authenticated but not permitted. **`detail` names the permission that was required**, so a
         *     caller can tell "you cannot do this" from "you cannot do this yet, ask for `users:write`".
         *     A client should not render an action it lacks the permission for at all -- a disabled
         *     control advertises a capability and generates a support ticket.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description No such resource **in this tenant**. A row belonging to another tenant is indistinguishable
         *     from one that does not exist, which is the intended behaviour.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description `version_conflict` when `If-Match` is stale, or `duplicate_sku` when a SKU is already
         *     taken within the tenant.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Validation failed. Also returned when a client sends a server-managed field on update, or
         *     sends `null` where the field should simply have been omitted — those are not the same
         *     thing.
         */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded. See the `RateLimit-*` headers. */
        TooManyRequests: {
            headers: {
                "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Page size. Pairs with `cursor`; there is no `offset` in this API. */
        Limit: number;
        /**
         * @description Opaque cursor from the previous page. Cursor pagination only — a deep `offset` on a large
         *     table is a sequential scan, so the parameter does not exist.
         */
        Cursor: string;
        /**
         * @description The `version` read from the resource. Required on every `PATCH`. The server checks it in
         *     the `UPDATE … WHERE version = $n` predicate; a stale value is `409 version_conflict`, not
         *     a silent no-op.
         *
         *     `version` travels here and never in the request body.
         */
        IfMatch: number;
    };
    requestBodies: never;
    headers: {
        /** @description Requests permitted in the current window. */
        "RateLimit-Limit": number;
        /** @description Requests left in the current window. */
        "RateLimit-Remaining": number;
        /** @description Seconds until the window resets. */
        "RateLimit-Reset": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    /** @description The refresh token, httpOnly, Secure, SameSite=Lax. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated. */
            200: {
                headers: {
                    /** @description The new refresh token. The old one is revoked. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    /** @description Clears the refresh token cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The seeded roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
